# Generated by Django 3.2.8 on 2021-10-30 17:32

from django.contrib.postgres.operations import CreateExtension

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]
    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('units', models.IntegerField(default=1)),
                ('single_unit_weight', models.IntegerField(default=1)),
                ('produce_name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=5000)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='box.giveaway')),
                ('given_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.serviceuser')),
            ],
        ),
    ]
