# Generated by Django 3.2.8 on 2021-10-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211030_1235'),
        ('box', '0003_box_given_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='given_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.serviceuser'),
        ),
    ]
