# Generated by Django 3.2.8 on 2021-10-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_auto_20211030_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giveaway',
            old_name='quantity',
            new_name='single_unit_weight',
        ),
        migrations.RenameField(
            model_name='giveaway',
            old_name='single_box_weight',
            new_name='units',
        ),
        migrations.AddField(
            model_name='giveaway',
            name='deadline',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giveaway',
            name='description',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
