# Generated by Django 3.2.8 on 2021-10-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='joined',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
