# Generated by Django 3.2.8 on 2021-10-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_serviceuser_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='last_name',
        ),
    ]
